server {
    listen 80;

    # DNS interno de Docker. Obligatorio para usar variables en proxy_pass.
    resolver 127.0.0.11 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # PROXY PARA DESPACHOS
    location /api/v1/despachos {
        # Al usar una variable, Nginx NO verifica si el host existe al arrancar.
        # Esto evita el error "host not found in upstream".
        set $backend_despachos despachos-api;
        proxy_pass http://$backend_despachos:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # PROXY PARA VENTAS
    location /api/v1/ventas {
        set $backend_ventas ventas-api;
        proxy_pass http://$backend_ventas:8081;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}